// <auto-generated />
using System;
using BibleStudyColabApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BibleStudyColabApi.Migrations
{
    [DbContext(typeof(BibleContext))]
    [Migration("20190422213957_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BibleStudyColabApi.Models.BibleVersion", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Abbreviation");

                    b.Property<string>("InfoUrl");

                    b.Property<string>("Language");

                    b.Property<string>("Version");

                    b.HasKey("Id");

                    b.ToTable("BibleVersions");
                });

            modelBuilder.Entity("BibleStudyColabApi.Models.Verse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BibleVersionId");

                    b.Property<string>("Book");

                    b.Property<int>("ChapterNumber");

                    b.Property<string>("Testament");

                    b.Property<string>("Text");

                    b.Property<int>("VerseNumber");

                    b.HasKey("Id");

                    b.HasIndex("BibleVersionId");

                    b.ToTable("Verses");
                });

            modelBuilder.Entity("BibleStudyColabApi.Models.Verse", b =>
                {
                    b.HasOne("BibleStudyColabApi.Models.BibleVersion", "BibleVersion")
                        .WithMany("Verses")
                        .HasForeignKey("BibleVersionId");
                });
#pragma warning restore 612, 618
        }
    }
}
